google_analytics: UA-xxxxxxxx-1
authorbox: disabled
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
highlighter: none
name: eroyx
description: We will take you on the fabulous world of exploration. Travel,
  Lifestyle, Culture, Movie, Food, Games, Dramas, Shows and much more...
baseurl: ""
url: https://eroyx.tk
disqus: eroyx
include:
  - _pages
logo: /assets/images/eroyx_ii.png
mailchimp-list: https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b
adsense:
  status: disabled
  adsense-data-ad-client: ca-pub-4944786899709076
  adsense-data-ad-slot: ""
permalink: /:title/
email: info@eroyx.tk
lazyimages: enabled
paginate_path: /page:num/
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
title: eroyx
favicon: /assets/images/eroyx_ii.png
collections:
  authors:
    output: true
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: /category/:name/
kramdown:
  syntax_highlighter_opts:
    disable: true
paginate: 9
exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
menu:
  - title: Home
    url: /
    badge: ""
  - title: Categories
    url: /categories
    badge: ""
  - title: Tags
    url: /tags
    badge: ""
  - title: Contact
    url: /contact
    badge: ""
  - title: About
    url: /about
    badge: eroyx
