name: eroyx
title: eroyx
description: We will take you on the fabulous world of exploration. Travel,
  Lifestyle, Culture, Movie, Food, Games, Dramas, Shows and much more...
baseurl: ""
paginate_path: /page:num/
paginate: 9
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
url: https://eroyx.tk

# Collections
collections:
  authors:
    output: true
  genre:
    output: true
collections:
  countries:
    output: true
collections:
  languages:
    output: true

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: /category/:name/

# Markdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
highlighter: none
include:
  - _pages
permalink: /:title/

# Exclude
exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
