name: eroyx
title: eroyx
description: We will take you on the fabulous world of exploration. Travel,
  Lifestyle, Culture, Movie, Food, Games, Dramas, Shows and much more...
baseurl: ""
paginate_path: "/_page/page:num/"
paginate: 9
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
url: https://eroyx.tk

# Collections
collections:
  franchises:
    output: true
    permalink: /franchise/:title/
  authors:
    output: true
  genre:
    output: true
    permalink: /genre/:title/
  country:
    output: true
    permalink: /country/:title/
  language:
    output: true
    permalink: /language/:title/
  subtitle:
    output: true
  director:
    output: true

# Defaults
defaults:
  # Franchises
  - scope:
      path: "franchises"
    values:
      layout: franchise
  # All genre
  - scope:
      path: "genre"
    values:
      layout: genre
  # All country
  - scope:
      path: "country"
    values:
      layout: country
  # Indian Language
  - scope:
      path: "language"
    values:
      layout: language

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: /category/:name/

# Markdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
highlighter: rouge
include:
  - _pages
permalink: /:path/:title/

# Exclude
exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
