backend:
  name: git-gateway
  branch: admin

publish_mode: editorial_workflow
site_url: https://eroyx.tk
display_url: https://eroyx.tk
logo_url: https://eroyx.tk/assets/images/favicon.png

media_folder: "assets/images"
collections:
  - label: "Global Site Settings"
    name: "site_config"
    editor:
      preview: false
    delete: false
    files:
      - label: "Genre"
        name: "genre"
        file: "_data/genre.yml"
        fields:
          - label: "Genre"
            name: "genre"
            widget: "list"
            required: false
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
                required: true
                hint: "Ex. Action"
              - label: "Font Awesome icon code"
                name: "icon"
                widget: "string"
                required: true
                hint: "Ex. fas fa-snowboarding"
      - label: "Country"
        name: "country"
        file: "_data/country.yml"
        fields:
          - label: "Countries"
            name: "countries"
            widget: "list"
            required: false
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
                required: true
                hint: "Ex. India"
  - label: "Authors"
    name: "authors"
    folder: "_authors"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    delete: false
    editor:
      preview: false
      delete: false
    fields:
      - label: "Shortname"
        name: "name"
        widget: "string"
        required: true
        hint: "Ex: john (Use samll letters)"
      - label: "Display Name"
        name: "display_name"
        widget: "string"
        required: true
        hint: "Ex: John Doe"
      - label: "Avatar"
        name: "avatar"
        widget: "image"
        required: false
        hint: "Use optimised images"
      - label: "Gravatar ID"
        name: "gravatar"
        widget: "string"
        required: false
        hint: "Ex: b1cc14991db7a456fcd761680bbc8f81"
      - label: "E-mail"
        name: "email"
        widget: "string"
        required: false
        hint: "Ex: john@example.com"
      - label: "Website"
        name: "web"
        widget: "string"
        required: false
        hint: "Ex: johdoe.me"
      - label: "Twitter Link"
        name: "twitter"
        widget: "string"
        required: false
        hint: "Ex: https://twitter.com/johndoe"
      - label: "About You"
        name: "description"
        widget: "text"
        required: false
  - label: "Genre"
    name: "genre"
    folder: "genre"
    create: true
    identifier_field: "title"
    slug: "{{slug}}"
    editor:
      preview: false
      delete: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Ex: Action"
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
        hint: "About the genre"
  - label: "Country"
    name: "country"
    folder: "country"
    create: true
    identifier_field: "title"
    slug: "{{slug}}"
    editor:
      preview: false
      delete: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Ex: India"
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
        hint: "About the country"
  - label: "Language"
    name: "language"
    folder: "language"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    editor:
      preview: false
      delete: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Ex: Malayalam"
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
        hint: "About the contents in particular language."
  - label: "Director"
    name: "director"
    folder: "director"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    editor:
      preview: false
      delete: false
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
        required: true
        hint: "Ex: James Cameron"
      - label: "About"
        name: "about"
        widget: "text"
        required: false
        hint: "About the director."
  - label: "Post"
    name: "post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "{{title}}"
    extension: "md"
    fields:
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss"
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Post Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Ex: My First Awesome Post!"
      - label: "Thumbnail"
        name: "image"
        widget: "image"
        required: true
        hint: "Use 730*400 image."
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
        required: true
        hint: "Use portrait posters."
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: [display_name]
        displayFields: [display_name]
        valueField: "name"
        required: true
        hint: "Create a author and select it."
      - label: "Genre"
        name: "genre"
        widget: "relation"
        collection: "genre"
        searchFields: [title]
        displayFields: [title]
        valueField: "title"
        required: true
        multiple: true
        hint: "Create a genre and select it."
      - label: "Country"
        name: "country"
        widget: "relation"
        collection: "country"
        searchFields: [title]
        displayFields: [title]
        valueField: "title"
        required: true
        hint: "Create a country and select it."
      - label: "Language"
        name: "language"
        widget: "relation"
        collection: "language"
        searchFields: [title]
        displayFields: [title]
        valueField: "title"
        required: false
        multiple: true
        hint: "Create a country and select it."
      - label: "Director"
        name: "director"
        widget: "relation"
        collection: "director"
        searchFields: [name]
        displayFields: [name]
        valueField: "name"
        required: false
        multiple: true
        hint: "Create a director and select it."
      - label: "Subtitle"
        name: "subtitle"
        widget: "list"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
            hint: "Ex: Malayalam"
          - label: "File Upload"
            name: "file"
            widget: "file"
            allow_multiple: false
            media_library:
              config:
                multiple: false
            required: false
        hint: "Ex. English, Malayalam"
      - label: "Duration"
        name: "duration"
        widget: "number"
        valueType: "float"
        min: 0
        step: 1
        required: false
        hint: "Should in minutes."
      - label: "Content Rating"
        name: "content_rating"
        widget: "select"
        options:
          - { label: "5+", value: "5+" }
          - { label: "10+", value: "10+" }
          - { label: "13+", value: "13+" }
          - { label: "16+", value: "16+" }
          - { label: "18+", value: "18+" }
      - label: "Movie Rating"
        name: "rating"
        widget: "number"
        valueType: "float"
        min: 0.0
        max: 10.0
        step: 0.1
        required: false
      - label: "Release Year"
        name: "year"
        widget: "number"
        valueType: "float"
        required: false
        hint: "Ex: 2020"
      - label: "Tags"
        name: "tags"
        widget: "list"
        hint: "Tags help to find the content in search."
      - label: "Put this on Recommended"
        name: "recommended"
        widget: "boolean"
        required: false
        default: false
        hint: "Put image shadow ON to show post image shadow."
      - label: "Image Shadow"
        name: "imageshadow"
        widget: "boolean"
        required: false
        default: true
        hint: "Put image shadow ON to show post image shadow."
      - label: "Youtube Trailer"
        name: "youtubeId"
        widget: "string"
        required: false
        hint: "Place the youtube link of trailer."
      - label: "Netflix Stream"
        name: "netflix"
        widget: "string"
        required: false
        hint: "Place the link to watch the movie on Netflix"
      - label: "Amazon Prime Streaming"
        name: "primeVideo"
        widget: "string"
        required: false
        hint: "Place the link to watch the movie on Amazon Prime"
      - label: "Other Streaming Link"
        name: "streamNow"
        widget: "string"
        required: false
        hint: "Place the link to watch the movie"
      - label: "Telegram Download Link"
        name: "telegram"
        widget: "string"
        required: false
        hint: "Place the telegram link of movie."
      - label: "Small Description"
        name: "description"
        widget: "text"
        required: false
        hint: "This text is used by search engines."
      - label: "Review"
        name: "body"
        widget: "markdown"
